env:
  global:
    - CC_TEST_REPORTER_ID=df733ab0e62764d8a7330092a8b80f1ac954b017d3e8573f8ec66e62f0a26490
language: node_js
node_js:
  - node
addons:
  code_climate:
    repo_token: df733ab0e62764d8a7330092a8b80f1ac954b017d3e8573f8ec66e62f0a26490
script:
  - npm test
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
